### ISSUE TITLE
Training on target dataset without pre-training on PhraseCut

### ISSUE THREAD

**Issue by VarunBelagali98** [kdwonn/SaG#3]
Hi authors,

Thanks for the work and releasing the code!

I am curious to understand the effect of pre-training on PhraseCut dataset.
In case if you have tried in your experiments, could you please let me know if PharseCut pre-training is necessary? 
Will directly training from scratch on RefCOCO/+/gref result in poor performance (Table 1)?

<img width="887" alt="sag" src="https://github.com/kdwonn/SaG/assets/41789813/4ed65167-25e6-4637-b29d-e273b1ccc00b">

**Comment by kdwonn** [comment]
Thanks for your interest in our work!

The results presented in the first row of the red box indicate the performance of our method when the model is trained solely on the Visual Genome (VG) dataset without fine-tuning on the target dataset (i.e., trained on VG and tested on RefCOCO variants directly). The second row within the red box shows the performance under standard settings, where the model is not pretrained on a larger image-text dataset but is only trained on the training split of the target benchmark. Additionally, we have not tested the method where pretraining on VG is followed by fine-tuning on another dataset. While this approach could potentially yield better performance, it has not been validated.

To address your question, pretraining on the PhraseCut dataset is not a requirement for our method. It was included in our experiments to facilitate a fair comparison with other open-vocabulary segmentation methods and to demonstrate the zero-shot capabilities of our model. Directly training from scratch on RefCOCO/+/gref without pretraining on PhraseCut (second row) yield the better performance compared to the model only pretrained on PhraseCut without finetuning (first row).

Hope that sheds more light. If you have additional questions, feel free to reach out!

**Comment by VarunBelagali98** [comment]
Hi ,
Thanks for the detailed explanation. 
I think I had misunderstood the table before. 
Apologies for that.

**Comment by VarunBelagali98** [comment]
question answered
